import os

BITGET_BASE = "https://api.bitget.com"
PRODUCT_TYPE = "USDT-FUTURES"
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

MIN_VOLUME = float(os.getenv("MIN_VOLUME", "1500000"))
MAX_SYMBOLS = int(os.getenv("MAX_SYMBOLS", "180"))
MA_LEN = int(os.getenv("MA_LEN", "20"))
COOLDOWN_MIN = int(os.getenv("COOLDOWN_MIN", "180"))
STATE_PATH = "docs/ha_state.json"

SKIP = {
    "SPYUSDT", "TSLAUSDT", "NVDAUSDT", "SOXLUSDT", "SOXSUSDT",
    "AAPLUSDT", "MSFTUSDT", "AMZNUSDT", "METAUSDT", "GOOGUSDT",
    "MSTRUSDT", "COINUSDT", "CRCLUSDT", "SPCXUSDT", "SAMSUNGUSDT",
    "SNDKUSDT", "MUUSDT", "SKHYUSDT", "SKHYNIXUSDT", "AMDUSDT",
    "INTCUSDT", "TQQQUSDT", "QQQUSDT", "JP225USDT", "NAS100USDT",
    "US30USDT", "XAUUSDT", "XAGUSDT", "CLUSDT", "XAUTUSDT", "PAXGUSDT",
    "AVGOUSDT", "ORCLUSDT",
}
